### ISSUE TITLE
fetch-system.streams CD harbor 적용

### ISSUE THREAD

**Issue by ikjeong** [Goboolean/fetch-system.streams#29]

**Comment by mulmuri** [comment]
test without docker container은 새로운 이슈에서 진행하고,
delete environment code는 위 작업이 끝나면 같이 마무리되므로 같이 진행하고,
kustomize update는 선행 작업 (https://github.com/Goboolean/infrastructure/issues/22) 이 필요하므로 나중에 진행하고
나머지가 다 되면 리뷰요청 주세용

**Comment by mulmuri** [comment]
push image to harbor registry -> 요건 CD라서, CI랑 CD도 별개의 이슈로 가져가면 좋을 것 같습니당

**Comment by mulmuri** [comment]
요고 이미지 harbo에 업로드 잘 됐나요? 캡쳐 한번 올려주세요 ㅎㅎ

**Comment by ikjeong** [comment]
![image](https://github.com/user-attachments/assets/1fb6aced-029f-4d3d-8ca9-00086b14a542)
